services:
  - type: web
    name: ekalipi-tts
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
      mkdir -p static/audio tmp
    startCommand: python -m gunicorn app:app --config gunicorn_config.py --bind "0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHON_MAX_THREADS
        value: 1
      - key: GUNICORN_TIMEOUT
        value: 300
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /status
    healthCheckTimeout: 60
    initialDeployHook: echo "Waiting for models to load..."
    plan: standard